### ISSUE TITLE
Unable to use the login() function since the latest Tapo P110 firmware update

### ISSUE THREAD

**Issue by RvP2001** [fishbigger/TapoP100#76] opened 2022-09-21 08:46 UTC
When calling the login() function, the following error occurs: "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"
This error happens in line 159 of the file PyP100.py and is caused by r.json().
My assumption is that the latest firmware version 1.0.16 Build 220624 Rel. 171733 changed something in the response message but I cannot figure out what it is exactly

**Comment by vladak** [comment] 2022-09-21 23:11
Happens to me to. I have a P110 with older firmware that works fine and bought a new P110 for which the firmware update was performed which no longer works.

The trouble is that the P110 with the newer firmware (1.0.16 in my case) returns plain HTML to the HTTP POST request done in `login()`:
```html
<html><body><center>200 OK</center></body></html>
```
instead of JSON payload like it used to be in the 1.0.7 version:
```json
{"error_code":0,"result":{"response":"... BASE64 encoded encrypted data located here ..."}}
```

**Comment by vladak** [comment] 2022-09-21 23:28
To experiment a bit with firmware 1.0.16, I changed the value of https://github.com/fishbigger/TapoP100/blob/4e0458ff300102f630d953ebb463bfd7dff05f7a/PyP100/PyP100.py#L146 (so that `self.cookie` was `"."`) and also https://github.com/fishbigger/TapoP100/blob/4e0458ff300102f630d953ebb463bfd7dff05f7a/PyP100/PyP100.py#L149 (so that `encrypt()` was called with `"."`) and in both cases it resulted in the `200 OK` HTML output.

My guess is that this is a reaction of the firmware to invalid input.

**Comment by pcollinson** [comment] 2022-09-22 05:19
This is happening with P100s too.

**Comment by pcollinson** [comment] 2022-09-22 15:02
Well a bit of investigation. The plugs are saying SHIP 2.0 in the response field. I'm suspecting that they are now using the Smart Home IP protocol - which is part of the EEBUS environment. This guess is somewhat reinforced by a packet dump I took on my network with the IOS client running. It shows conversations between my devices and an Amazon client to make the plugs change state. So the app is not talking to the plug, but is requesting a change from their server which in turn is changing the plug state down a webconnect link. SHIP is also used by my heating system.

SHIP is pretty well hidden, although eebus.org does allow you to download a spec of the protocol, it's xml embedded in JSON.

I think that the '200 OK' response is a 'you aren't talking my protocol' message.

However, this is all deeply frustrating.

**Comment by tking2** [comment] 2022-09-22 18:17
@pcollinson From inspecting traffic on my own plugs, the Server header with `SHIP 2.0` is present prior to the firmware update, so I don't think anything has changed here.

It does appear to solely be related to login, as handshake works OK, and captured traffic implies switching power is the same, although I haven't been able to capture the handshake from the TAPO app to grab the AES key to decrypt. But I expect this is likely a payload structure change rather than a protocol change.

If anyone has the ability to dump the latest fimrware, I can take a look to identify how the login protocol or payload structure has changed.

**Comment by tking2** [comment] 2022-09-22 19:40
Turns out nothing had changed! Kicked myself when I figure out the mistake.

It appears that new firmware versions perform stricter validation on the session cookie. In a previously harmless mistake, a semicolon was kept on the end of the session cookie. P100 v1.1.0 and P110 v1.0.16 now treat this as invalid.

Tested and can now control plugs again after applying PR!

**Comment by pcollinson** [comment] 2022-09-22 19:44
Yay! Back in business.

**Comment by vladak** [comment] 2022-09-22 19:45
Confirmed - the change in the PR fixes the problem.

**Comment by NyquistFX** [comment] 2022-09-22 22:12
Many thanks to all!
Applied the update and getting **data** instead of errors.. Happy days!

**Comment by lemoustachiste** [comment] 2022-09-23 13:51
So I'm pretty unlucky, I received the tp110 2 days ago, set up the raspberry pi and tplink account yesterday (updating the firmware), today I'm working on my python script when I get this error...

Any idea when the fix will be released?

Thanks

**Comment by vladak** [comment] 2022-09-24 14:12
> So I'm pretty unlucky, I received the tp110 2 days ago, set up the raspberry pi and tplink account yesterday (updating the firmware), today I'm working on my python script when I get this error...
> 
> Any idea when the fix will be released?
> 
> Thanks

depends on @fishbigger , maybe it will help if you support him via the http://buymeacoffee.com/fishbigger on his profile page.

**Comment by RvP2001** [comment] 2022-09-26 06:18
Thanks guys! I changed
`self.cookie = r.headers["Set-Cookie"][:-13]` in line 128 of PyP100.py to
`self.cookie = r.headers["Set-Cookie"][:-14]` and now it works again!

**Closed** 2022-10-26 16:59 UTC
